# Generated by Django 5.2.2 on 2025-06-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeorder',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='processed_at',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed'), (4, 'Canceled')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Credit_Increase'), (2, 'Charge_Sale')], db_index=True),
        ),
    ]
