# Generated by Django 5.2.2 on 2025-06-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_chargeorder_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='seller.creditrequest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='seller.phonenumber'),
        ),
    ]
