# Generated by Django 5.2.2 on 2025-06-09 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_transaction_credit_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_credit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='seller.creditrequest'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='seller.phonenumber'),
        ),
    ]
