# Generated by Django 5.2.2 on 2025-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_creditrequest_processed_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('seller', 'amount'), name='unique_pending_credit_request_per_seller_amount'),
        ),
    ]
