# Generated by Django 5.2.2 on 2025-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_creditrequest_unique_pending_credit_request_per_seller_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
