# Generated by Django 5.2.2 on 2025-06-11 04:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chargeorder',
            name='charge_orde_seller__23f157_idx',
        ),
        migrations.RemoveIndex(
            model_name='chargeorder',
            name='charge_orde_status_7f2394_idx',
        ),
        migrations.RemoveField(
            model_name='chargeorder',
            name='charge_amount',
        ),
        migrations.RemoveField(
            model_name='chargeorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='chargeorder',
            name='transaction',
        ),
        migrations.AddField(
            model_name='chargeorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='charge_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='seller.chargeorder'),
        ),
        migrations.AddIndex(
            model_name='chargeorder',
            index=models.Index(fields=['seller'], name='charge_orde_seller__4bbf74_idx'),
        ),
        migrations.AddIndex(
            model_name='chargeorder',
            index=models.Index(fields=['created_at'], name='charge_orde_created_d43ec1_idx'),
        ),
    ]
